### ISSUE TITLE
Add option parameters for credential fields

### ISSUE THREAD

**Issue by tenevdev** [jaredhanson/passport-oauth2-client-password#6]
I think it is a good idea to be able to change the defaults `client_id` and `client_secret` if other names are preferred. This feature is currently available in passport-local and I don't think it is a problem adding it to this strategy as well. The requested change would let one use the following:
```javascript
passport.use(new ClientPasswordStrategy({
    clientIdField: 'clientId',
    clientSecretField: 'clientSecret'
}, function(clientId, clientSecret, done) { ... }
}))
```
I have noticed that passport-local also checks `req.query` for the fields specified, which could be considered in this strategy. When I have some free time I might submit a pull request provided that it will be accepted.

**Comment by jaredhanson** [comment]
The fields are what they are because that is what is mandated by the [specification](https://tools.ietf.org/html/rfc6749#section-2.3.1).  It's the goal of this strategy to conform exactly to the strategy.

`passport-local` is a separate concern, but for what its worth, that allows configuration options because there is no standard for form-based authentication.
